<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UserManage\Module'                        => __DIR__ . '/Module.php',
    'UserManage\Controller\UserManageController' => __DIR__ . '/src/UserManage/Controller/UserManageController.php',
    'UserManageTest\Framework\TestCase'        => __DIR__ . '/tests/UserManage/Framework/TestCase.php',
    'UserManageTest\SampleTest'                => __DIR__ . '/tests/UserManage/SampleTest.php',
);
