<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ImageDisplay\Module'                        => __DIR__ . '/Module.php',
    'ImageDisplay\Controller\ImangeDisplayControllerController' => __DIR__ . '/src/ImageDisplay/Controller/ImangeDisplayControllerController.php',
    'ImageDisplayTest\Framework\TestCase'        => __DIR__ . '/tests/ImageDisplay/Framework/TestCase.php',
    'ImageDisplayTest\SampleTest'                => __DIR__ . '/tests/ImageDisplay/SampleTest.php',
);
