<?php

$title = 'user profile list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('userprofile', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($userprofiles as $userprofile) : ?>
<tr>
    <td><?php echo $this->escapeHtml($userprofile->getDisplay_name());?></td>
    <td><?php echo $this->escapeHtml($userprofile->getActual_name());?></td>
    <td>
        <a href="<?php echo $this->url('userprofile',
            array('action'=>'edit', 'id' => $userprofile->getUid()));?>">Edit</a>
        <a href="<?php echo $this->url('userprofile',
            array('action'=>'delete', 'id' => $userprofile->getUid()));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>