<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Recommendation\Module'                        => __DIR__ . '/Module.php',
    'Recommendation\Controller\RecommendationControllerController' => __DIR__ . '/src/Recommendation/Controller/RecommendationControllerController.php',
    'RecommendationTest\Framework\TestCase'        => __DIR__ . '/tests/Recommendation/Framework/TestCase.php',
    'RecommendationTest\SampleTest'                => __DIR__ . '/tests/Recommendation/SampleTest.php',
);
